name: Deploy ke Server

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: self-hosted
    environment: Production

    env:
      APP_DIR: ${{ vars.APP_DIR }}

    steps:
      - name: Deploy
        run: |
          set -e

          APP_DIR="${APP_DIR:-/var/www/html/project/SI-SIDANG-FTTM-ITB}"

          echo "==> Masuk ke $APP_DIR"
          cd "$APP_DIR"

          echo "==> Update source dari GitHub"
          git fetch origin main
          git reset --hard origin/main

          echo "==> Composer install"
          composer install \
            --no-interaction \
            --no-dev \
            --prefer-dist \
            --optimize-autoloader

          echo "==> Clear cache"
          php artisan optimize:clear

          echo "==> Optimize Laravel"
          php artisan optimize

          echo "==> DEPLOY SELESAI"